apiVersion: apps/v1beta1
kind: Deployment 
metadata:
  name: ssh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssh
    spec:
      containers:
        - name: ssh
          image: registry.test.oceanstack.slancer.com/ssh:224
          ports:
            - containerPort: 8080
          resources:
            requests: 
              cpu: "250m"
              memory: "64Mi"
            limits: #资源最高限制
              memory: "128Mi"
              cpu: "500m" #0.5核cpu

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-service
  labels:
    name: ssh-service
spec:
  type: NodePort      #这里代表是NodePort类型的
  ports:
  - port: 8080          #这里的端口和clusterIP对应，供内部访问。
    targetPort: 8080  #端口一定要和container暴露出来的端口对应
    protocol: TCP
    nodePort: 32144   # 所有的节点都会开放此端口，此端口供外部调用。
  selector:
    app: ssh
